## Corpus file

break_text         <- 'Break in comparability of data, as explained in the relevant country
                       metadata notes. In these instances, data after the symbol do not form
                       a consistent series with those for earlier dates. The break symbols not
                       explained in the country metadata notes can show a  point of splice,
                       where series having different base years are linked. They can also
                       point out a change in magnitude for high-inflation countries.'

fsi_fred_ind       <- hash(c(FSCR_PT="CRELTL",
                             FSERA_PT="RETAST",
                             FSERE_PT="RETEQT",
                             FSHG_PT="HDTGPD",
                             FSKRC_PT="RCTRWA",
                             FSLS_PT="LATSTL",
                             FSLT_PT="LQASRT",
                             FSREPCR_PC_CP_A_PT="COMREP",
                             FSREPRR_PC_CP_A_PT="RESREP",
                             FSRR_PT="RRELTL",
                             FSTD_PT="TOTDTE",
                             FSKRTC_PT="RT1CRA"))

ifs_fred_ind       <- hash(c(FID_PA="INTDSR",
                             FIGB_PA="INTGSB",
                             FIGB_SA_PA="INTGSB",
                             FITB_PA="INTGST",
                             FM0_SA_XDC="MYAGM0",
                             FM0_XDC="MYAGM0",
                             FM1_A1_XDC="MAM1A1",
                             FM1_A2_SA_XDC="MAM1A2",
                             FM1_A2_XDC="MAM1A2",
                             FM1_A3_SA_XDC="MAM1A3",
                             FM1_A3_XDC="MAM1A3",
                             FM1_EUR="MYAGM1",
                             FM1_SA_USD="MYAGM1",
                             FM1_SA_XDC="MYAGM1",
                             FM1_USD="MYAGM1",
                             FM1_XDC="MYAGM1",
                             FM2_A1_XDC="MAM2A1",
                             FM2_A2_SA_XDC="MAM2A2",
                             FM2_A2_XDC="MAM2A2",
                             FM2_A3_SA_XDC="MAM2A3",
                             FM2_A3_XDC="MAM2A3",
                             FM2_A4_SA_XDC="MAM2A4",
                             FM2_EUR="MYAGM2",
                             FM2_SA_USD="MYAGM2",
                             FM2_SA_XDC="MYAGM2",
                             FM2_USD="MYAGM2",
                             FM2_XDC="MYAGM2",
                             FM3_A1_XDC="MAM3A1",
                             FM3_A2_SA_XDC="MAM3A2",
                             FM3_A2_XDC="MAM3A2",
                             FM3_A3_XDC="MAM3A3",
                             FM3_A4_XDC="MAM3A4",
                             FM3_EUR="MYAGM3",
                             FM3_SA_USD="MYAGM3",
                             FM3_SA_XDC="MYAGM3",
                             FM3_USD="MYAGM3",
                             FM3_XDC="MYAGM3",
                             FM4_A1_XDC="MAM4A1",
                             FM4_A2_XDC="MAM4A2",
                             FM4_A3_XDC="MAM4A3",
                             FM4_SA_XDC="MYAGM4",
                             FM4_XDC="MYAGM4",
                             FMA_USD="BASMNY",
                             FMA_XDC="BASMNY",
                             FMB_USD="BRDMNY",
                             FMB_XDC="BRDMNY",
                             RAXG_USD="TRESEG",
                             RAXG_XDR="TRESEG",
                             TMG_CIF_USD="VALIMP",
                             TXG_FOB_USD="VALEXP"))

fsi_fred_nat       <- hash(c(AU='Australia',
                             BR='Brazil',
                             CA='Canada',
                             FR='France',
                             DE='Germany',
                             IT='Italy',
                             KR='Korea, Republic of',
                             MX='Mexico',
                             PL='Poland',
                             ES='Spain',
                             UK='United Kingdom',
                             US='United States',
                             ZA='South Africa'))

ifs_fred_nat       <- hash(c(AR='Argentina',
                             AU='Australia',
                             BR='Brazil',
                             CA='Canada',
                             CN='China, P.R.: Mainland',
                             DE='Germany',
                             ES='Spain',
                             EZ='Euro Area',
                             FR='France',
                             ID='Indonesia',
                             IN='India',
                             IR='Iran, Islamic Republic of',
                             IT='Italy',
                             JP='Japan',
                             KR='Korea, Republic of',
                             MX='Mexico',
                             PL='Poland',
                             RU='Russian Federation',
                             SA='Saudi Arabia',
                             TR='Turkey',
                             TW='Taiwan Province of China',
                             UK='United Kingdom',
                             US='United States',
                             ZA='South Africa'))

fred_units         <- hash(c(PA  = '193',
                             PT  = '163',
                             USD = '052',
                             XDC = '189',
                             XDR = '194'))