## Corpus file

break_text     <- 'Break in comparability of data, as explained in the relevant country metadata notes. In these instances, data after the symbol do not form a consistent series with those for earlier dates. The break symbols not explained in the country metadata notes can show a  point of splice, where series having different base years are linked. They can also point out a change in magnitude for high-inflation countries.'

fsi_indicators <- c("FSREPCR_PC_CP_A_PT",
                    "FSCR_PT",
                    "FSHG_PT",
                    "FSLS_PT",
                    "FSLT_PT",
                    "FSKRC_PT",
                    "FSREPRR_PC_CP_A_PT",
                    "FSRR_PT",
                    "FSERA_PT",
                    "FSERE_PT",
                    "FSKRTC_PT",
                    "FSTD_PT")

fred_fsi_ind   <- c('COMREP',
                    'CRELTL',
                    'HDTGPD',
                    'LATSTL',
                    'LQASRT',
                    'RCTRWA',
                    'RESREP',
                    'RRELTL',
                    'RETAST',
                    'RETEQT',
                    'RT1CRA',
                    'TOTDTE')

fsi_fred_ind   <- hash(c(COMREP="FSREPCR_PC_CP_A_PT",
                         CRELTL="FSCR_PT",
                         HDTGPD="FSHG_PT",
                         LATSTL="FSLS_PT",
                         LQASRT="FSLT_PT",
                         RCTRWA="FSKRC_PT",
                         RESREP="FSREPRR_PC_CP_A_PT",
                         RRELTL="FSRR_PT",
                         RETAST="FSERA_PT",
                         RETEQT="FSERE_PT",
                         RT1CRA="FSKRTC_PT",
                         TOTDTE="FSTD_PT"))

# ifs_indicators <- c('FMB_XDC',
#                     'FMB_USD',
#                     'FMA_USD',
#                     'FMA_SA_USD',
#                     'FMA_XDC',
#                     'FMA_SA_XDC',
#                     'FMA_A1_XDC',
#                     'FMA_A2_XDC',
#                     'FM0_XDC',
#                     'FM0_SA_XDC',
#                     'FM1_XDC',
#                     'FM1_SA_XDC',
#                     'FM1_USD',
#                     'FM1_SA_USD',
#                     'FM1_EUR',
#                     'FM1_A1_XDC',
#                     'FM1_A2_XDC',
#                     'FM1_A3_XDC',
#                     'FM2_XDC',
#                     'FM2_USD',
#                     'FM2_EUR',
#                     'FM2_A1_XDC',
#                     'FM2_A2_XDC',
#                     'FM2_A3_XDC',
#                     'FM3_XDC',
#                     'FM3_EUR',
#                     'FM3_USD',
#                     'FM3_A1_XDC',
#                     'FM3_A3_XDC',
#                     'FM3_A4_XDC',
#                     'FM4_XDC',
#                     'FM4_A1_XDC',
#                     'FM4_A2_XDC',
#                     'FM4_A3_XDC',
#                     'TXG_FOB_USD',
#                     'TMG_CIF_USD',
#                     'RAXG_XDR',
#                     'RAXG_USD',
#                     'FID_PA',
#                     'FITB_PA',
#                     'FIGB_SA_PA',
#                     'FIGB_PA')

ifs_fred_ind  <- hash(c(FID_PA="INTDSR",
                        FIGB_PA="INTGSB",
                        FIGB_SA_PA="INTGSB",
                        FITB_PA="INTGST",
                        FM0_SA_XDC="MYAGM0",
                        FM0_XDC="MYAGM0",
                        FM1_A1_XDC="MAM1A1",
                        FM1_A2_SA_XDC="MAM1A2",
                        FM1_A2_XDC="MAM1A2",
                        FM1_A3_SA_XDC="MAM1A3",
                        FM1_A3_XDC="MAM1A3",
                        FM1_EUR="MYAGM1",
                        FM1_SA_USD="MYAGM1",
                        FM1_SA_XDC="MYAGM1",
                        FM1_USD="MYAGM1",
                        FM1_XDC="MYAGM1",
                        FM2_A1_XDC="MAM2A1",
                        FM2_A2_SA_XDC="MAM2A2",
                        FM2_A2_XDC="MAM2A2",
                        FM2_A3_SA_XDC="MAM2A3",
                        FM2_A3_XDC="MAM2A3",
                        FM2_A4_SA_XDC="MAM2A4",
                        FM2_EUR="MYAGM2",
                        FM2_SA_USD="MYAGM2",
                        FM2_SA_XDC="MYAGM2",
                        FM2_USD="MYAGM2",
                        FM2_XDC="MYAGM2",
                        FM3_A1_XDC="MAM3A1",
                        FM3_A2_SA_XDC="MAM3A2",
                        FM3_A2_XDC="MAM3A2",
                        FM3_A3_XDC="MAM3A3",
                        FM3_A4_XDC="MAM3A4",
                        FM3_EUR="MYAGM3",
                        FM3_SA_USD="MYAGM3",
                        FM3_SA_XDC="MYAGM3",
                        FM3_USD="MYAGM3",
                        FM3_XDC="MYAGM3",
                        FM4_A1_XDC="MAM4A1",
                        FM4_A2_XDC="MAM4A2",
                        FM4_A3_XDC="MAM4A3",
                        FM4_SA_XDC="MYAGM4",
                        FM4_XDC="MYAGM4",
                        FMA_USD="BASMNY",
                        FMA_XDC="BASMNY",
                        FMB_USD="BRDMNY",
                        FMB_XDC="BRDMNY",
                        RAXG_USD="TRESEG",
                        RAXG_XDR="TRESEG",
                        TMG_CIF_USD="VALIMP",
                        TXG_FOB_USD="VALEXP"))

# fred_ifs_ind   <- c('INTDSR',
#                     'INTGSB',
#                     'INTGST',
#                     'MYAGM0',
#                     'MYAGM1',
#                     'MAM1A1',
#                     'MAM1A2',
#                     'MAM1A3',
#                     'MYAGM2',
#                     'MAM2A1',
#                     'MAM2A2',
#                     'MAM2A3',
#                     'MAM2A4',
#                     'MYAGM3',
#                     'MAM3A2',
#                     'MAM3A3',
#                     'MAM3A4',
#                     'MYAGM4',
#                     'MAM4A1',
#                     'MAM4A2',
#                     'MAM4A3',
#                     'BASMNY',
#                     'BRDMNY',
#                     'TRESEG',
#                     'VALIMP',
#                     'VALEXP')

fsi_countries  <- c('Australia','Brazil','Canada','France','Germany','Italy',
                    'Korea, Republic of','Mexico','Poland','Spain','United Kingdom',
                    'United States','South Africa')

fsi_fred_nat   <- hash(c(AU='Australia',
                         BR='Brazil',
                         CA='Canada',
                         FR='France',
                         DE='Germany',
                         IT='Italy',
                         KR='Korea, Republic of',
                         MX='Mexico',
                         PL='Poland',
                         ES='Spain',
                         UK='United Kingdom',
                         US='United States',
                         ZA='South Africa'))

ifs_countries  <- c('Argentina','Australia','Brazil','Canada','China, P.R.: Mainland',
                    'Germany','Spain','Euro Area','France','Indonesia','India',
                    'Iran, Islamic Republic of','Italy','Japan','Korea, Republic of',
                    'Mexico','Poland','Russian Federation','Saudi Arabia','Turkey',
                    'Taiwan Province of China','United Kingdom','United States','South Africa')

ifs_fred_nat   <- hash(c(AR='Argentina',
                         AU='Australia',
                         BR='Brazil',
                         CA='Canada',
                         CN='China, P.R.: Mainland',
                         DE='Germany',
                         ES='Spain',
                         EZ='Euro Area',
                         FR='France',
                         ID='Indonesia',
                         IN='India',
                         IR='Iran, Islamic Republic of',
                         IT='Italy',
                         JP='Japan',
                         KR='Korea, Republic of',
                         MX='Mexico',
                         PL='Poland',
                         RU='Russian Federation',
                         SA='Saudi Arabia',
                         TR='Turkey',
                         TW='Taiwan Province of China',
                         UK='United Kingdom',
                         US='United States',
                         ZA='South Africa'))

fred_units     <- hash(c(PA  = '193',
                         PT  = '163',
                         USD = '052',
                         XDC = '189',
                         XDR = '194'))